---
# tasks file for lb-tier
- name: install HAProxy
  yum:
    name: haproxy
    state: latest

- name: enable HAProxy
  service:
    name: haproxy
    enabled: yes

- name: start HAProxy
  service:
    name: haproxy
    state: started
    
- name: configure restart HAProxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart HAProxy
